### PR TITLE
Bump go version to 1.15

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by msau42** [comment]
/lgtm
/approve
/hold 
Can you add a release note?

Also this will probably need rebasing after https://github.com/kubernetes-csi/external-attacher/pull/251 merges

**Comment by pohly** [comment]
> Can you add a release note?

"Build with Go 1.15" was already added as release note via https://github.com/kubernetes-csi/external-attacher/pull/245

As far as I understand it, bumping the version in go.mod has no real impact. I tried with some other repo and it still built fine also with older Go, so Go isn't even enforcing the minimal version. At best it provides some hints. There's an open bug about this vagueness: https://github.com/golang/go/issues/30791

**Comment by pohly** [comment]
Having said that, Go 1.15 is what we use for testing and building, so specifying that in the go.mod file seems reasonable to me.

lgtm

**Pull request merged**
