### PR TITLE
Added gcr.io push to Makefile

### PR DESCRIPTION
**Pull request by davidz627**
Added gcr.io push to Makefile for automatic pushing

### CODE REVIEW

**Comment by davidz627** [comment]
WIP: registry name is not final.

**Comment by davidz627** [comment]
Paths finalized. PTAL

**Comment by saad-ali** [comment]
> I am not sure we need two docker repositories for one image. Which one is authoritative then? Most people can't push to gcr.io and it's outside of our control. These repos will get out of sync quickly.

It's a requirement for containers that GKE will depend on. We do this for many of the existing Kubernetes containers. The permissions thing is something that is a known issue and is being worked on. Consider this a manual step that Google team will execute until the permission issues are resolved.

**Comment by jsafrane** [comment]
ok, I'll merge it, please rebase.

**Comment by saad-ali** [comment]
Discussed with Jan offline, we will close this PR, and come up with another process for syncing these images to gcr.

**Pull request closed without merging**
