### PR TITLE
Add CSI Migration logic for attach/detach

### PR DESCRIPTION
**Pull request by davidz627**
This PR adds migration logic for attach/detach.
This logic will get called upon from the code-paths introduced in: https://github.com/kubernetes/kubernetes/pull/69830

/assign @jsafrane @saad-ali 

/cc @lpabon

### CODE REVIEW

**Comment by jsafrane** [comment]
The code looks great, however, can you please add a test that creates PV 
 with GCEPersistentDiskVolumeSource  and tests that CSI is called with the right arguments? You'll probably need to change `testAttacherName` to GCE, that's fine.

**Comment by davidz627** [comment]
@jsafrane I have added unit tests for the translation functionality :+1:

**Comment by davidz627** [comment]
@jsafrane PTAL when you have the time

**Comment by jsafrane** [comment]
/approve
?

**Pull request merged**
