### PR TITLE
Update dependency go modules for k8s v1.26.0

### PR DESCRIPTION
**Pull request by sunnylovestiramisu**
Ran kubernetes-csi/csi-release-tools go-get-kubernetes.sh -p 1.26.0

### CODE REVIEW

**Comment by jsafrane** [comment]
/release-note-none
?

**Comment by jsafrane** [comment]
/lgtm
bad day today :-)

**Comment by humblec** [comment]
@sunnylovestiramisu looks like some dependencies are still with rc tag https://github.com/kubernetes-csi/external-attacher/pull/395/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L17 or see #396 . considering you have filed PRs in sidecar repos, it would be better to revisit the existing PRs too

**Comment by humblec** [comment]
> @humblec good catch, I missed that one.

yw :+1:

**Comment by sunnylovestiramisu** [comment]
I was running the script go-get-kubernetes.sh and this is what the script generated. Do we usually manually update dependencies after running the script? It happened twice already for both 1.26.0-rc and 1.26.0.

**Comment by msau42** [comment]
I think it's worth digging more into the script to figure out why it's not updating those. We want to get to a state where the script is reliable and doesn't require modifying by hand afterwards

**Pull request merged**
