### PR TITLE
CSI 0.2.0 breaking changes refactor

### PR DESCRIPTION
**Pull request by sbezverk**
Refactor external attacher with new changes introduced in CSI spec 0.2.0

### CODE REVIEW

**Comment by jsafrane** [comment]
Thanks for the PR. The code itself looks fine, however bump `csiVersion` in connection.go please.

And could you please add some check at startup that the driver actually supports 0.2.0, probably in another PR?

**Comment by sbezverk** [comment]
@jsafrane Thank you for your review, I will change the version and with the following up PR will add a check for 0.2.0.

**Comment by sbezverk** [comment]
@jsafrane @rootfs at this point breaking CSI Spec changes are merged into master and CSI sanity test changes are also merged. I would appreciate  if you could check this PR.
I had to bump up client-go version to 6.0.0 as ```dep``` was failing with 5.0.1. Thanks a lot. Serguei

**Comment by jsafrane** [comment]
lgtm

**Pull request merged**
