### PR TITLE
Upgrade csi-lib-utils to version 0.8.1

### PR DESCRIPTION
**Pull request by Jiawei0227**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Upgrade csi-lib-utils to version 0.8.1

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Add `process_start_time_seconds` metric.
```

### CODE REVIEW

**Comment by Jiawei0227** [comment]
I will cherrypick the change to previous branch. No need for 3.0
/close

**Comment by msau42** [comment]
Why do we not need 3.0? If we cherry-pick to older branches, we should make sure all later releases also have the change

**Comment by Jiawei0227** [comment]
Okay, sure. I will reopen this.

**Pull request merged**
