### PR TITLE
Temporarily calling CSINodeInfo API directly instead of using a lister

### PR DESCRIPTION
**Pull request by verult**
Mitigation around https://github.com/kubernetes/kubernetes/issues/71052, which is causing CSI e2e test failures in https://github.com/kubernetes/kubernetes/issues/70760.

/assign @msau42 
/cc @davidz627 @saad-ali

### CODE REVIEW

**Comment by msau42** [comment]
lgtm besides test failures

**Comment by pohly** [comment]
Is there a bug open for reverting this change and fixing the underlying issue? Or how is it getting tracked?

**Comment by verult** [comment]
@pohly I updated the comment in https://github.com/kubernetes/kubernetes/issues/71052 to track the reverting of this PR. Thanks for pointing that out!

**Pull request merged**
